# Generated by Django 3.0.5 on 2020-10-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0007_auto_20201003_1130'),
        ('user', '0002_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='comparator.Product')),
                ('user', models.ForeignKey(blank=True, db_column='users', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StoreProduct',
                'managed': 'True',
            },
        ),
        migrations.CreateModel(
            name='FollowPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.ForeignKey(blank=True, db_column='price', null=True, on_delete=django.db.models.deletion.CASCADE, to='comparator.Price')),
                ('user', models.ForeignKey(blank=True, db_column='users', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FollowPrice',
                'managed': 'True',
            },
        ),
    ]
