# Generated by Django 3.0.5 on 2020-07-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'Site',
                'managed': 'True',
            },
        ),
    ]
