# Generated by Django 3.0.5 on 2020-08-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0003_auto_20200801_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comparator.Category')),
            ],
            options={
                'db_table': 'LowCategory',
                'managed': 'True',
            },
        ),
    ]
