# Generated by Django 3.0.5 on 2020-10-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0006_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': 'True'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
